### ISSUE TITLE
Send the drivers required

### ISSUE THREAD

**Issue by Eeman1113** [ashklempton/plant-monitoring#1] opened 2019-11-23 11:19 UTC
Drivers bro drivers!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ashkln** [comment] 2019-11-23 14:07
If you have the arduino with you run this
pip install serial flask gunicorn Flask-cors

**Comment by AbhisekGanguly** [comment] 2019-11-24 09:39
closing this issue as the problem is solved.

**Closed as completed by AbhisekGanguly** 2019-11-24 09:39 UTC
